#!/usr/bin/env bash
# 配布物に含まれる依存ライブラリのライセンスを THIRD-PARTY-NOTICES.txt に書き出す。
# `pnpm notices` から呼ばれる。依存を足したり上げたりしたら流し直してコミットする
# (lib.rs のテストが、直接依存がこのファイルに載っているかを見る)。
#
# 節は 3 つ:
# - JavaScript: package.json の dependencies を推移的に (pnpm licenses list --prod)。
#   加えて、devDependencies にあるがビルドで webview に bundle されるものを
#   BUNDLED_DEV_PACKAGES に列挙する (svelte / SvelteKit のランタイム、svelte-sonner と
#   その依存、CSS に入る tailwindcss、フォントを同梱する bootstrap-icons)。
#   この一覧は `vite build` に sourcemap を出させ、sources に現れる node_modules の
#   パッケージを数えて決めた。devDependencies に bundle されるものを足したらここにも足す。
# - Rust: cargo-about (`cargo install cargo-about --locked --features cli`)。
#   設定は src-tauri/about.toml、書式は src-tauri/about.hbs。
# - Native: crate が C / C++ のソースを同梱して静的リンクするライブラリ (OpenSSL / libssh2 /
#   zlib / SQLite / DuckDB が third_party に同梱するもの)。crate 自身のライセンスは Rust 節に
#   出るが、同梱しているライブラリのライセンスは別物なので、crate のソース (DuckDB は同じ
#   version のタグの DuckDB リポジトリ。GitHub へのネットワーク接続が要る) から本文を読んで載せる。
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD-PARTY-NOTICES.txt"

if ! cargo about --version >/dev/null 2>&1; then
  echo "Error: cargo-about is not installed. Run: cargo install cargo-about --locked --features cli" >&2
  exit 1
fi
if [ ! -d node_modules ]; then
  echo "Error: node_modules is missing. Run: pnpm install" >&2
  exit 1
fi

# 同じディレクトリに作る。別ファイルシステムの /tmp からの mv はコピーになり、途中で
# 止まると壊れた出力が残る
TMP=$(mktemp "${OUT}.XXXXXX")
PROD_JSON=$(mktemp "${OUT}.prod.XXXXXX")
ALL_JSON=$(mktemp "${OUT}.all.XXXXXX")
METADATA_JSON=$(mktemp "${OUT}.meta.XXXXXX")
trap 'rm -f "$TMP" "$PROD_JSON" "$ALL_JSON" "$METADATA_JSON"' EXIT

pnpm licenses list --prod --json > "$PROD_JSON"
pnpm licenses list --json > "$ALL_JSON"
cargo metadata --manifest-path src-tauri/Cargo.toml --locked --format-version 1 > "$METADATA_JSON"

{
  cat <<'HEADER'
THIRD-PARTY NOTICES

Queryfolio bundles the open source libraries listed below. Each entry gives the
license, the packages it applies to, and the license text as shipped by the
package. Generated by scripts/generate-third-party-notices.sh; do not edit by hand.

################################################################################
# JavaScript packages (bundled into the web view)
################################################################################

HEADER

  PROD_JSON="$PROD_JSON" ALL_JSON="$ALL_JSON" METADATA_JSON="$METADATA_JSON" node - <<'NODE'
const fs = require("fs");
const path = require("path");

const crates = new Set(
  JSON.parse(fs.readFileSync(process.env.METADATA_JSON, "utf8")).packages.map((p) => p.name),
);

const BUNDLED_DEV_PACKAGES = [
  "@sveltejs/kit",
  "bootstrap-icons",
  "clsx",
  "esm-env",
  "runed",
  "svelte",
  "svelte-sonner",
  "tailwindcss",
];

const flatten = (file) =>
  Object.values(JSON.parse(fs.readFileSync(file, "utf8"))).flat();

const packages = new Map();
const add = (entry) => {
  if (entry.versions.length !== 1) {
    // 複数 version が入っていると、どれが bundle されたかをここでは決められない
    throw new Error(`${entry.name} has several versions: ${entry.versions.join(", ")}`);
  }
  packages.set(entry.name, { name: entry.name, version: entry.versions[0], dir: entry.paths[0] });
};
for (const entry of flatten(process.env.PROD_JSON)) add(entry);
const all = flatten(process.env.ALL_JSON);
for (const name of BUNDLED_DEV_PACKAGES) {
  const entry = all.find((e) => e.name === name);
  if (!entry) throw new Error(`${name} is not installed`);
  add(entry);
}

for (const pkg of [...packages.values()].sort((a, b) => a.name.localeCompare(b.name))) {
  const manifest = JSON.parse(fs.readFileSync(path.join(pkg.dir, "package.json"), "utf8"));
  const repo =
    typeof manifest.repository === "string" ? manifest.repository : manifest.repository?.url;
  // LICENSE.spdx のような SPDX のメタデータは本文ではないので除く
  const files = fs
    .readdirSync(pkg.dir)
    .filter((f) => /^(LICEN[CS]E|COPYING|NOTICE)/i.test(f) && !/\.spdx$/i.test(f))
    .sort();
  console.log("=".repeat(80));
  console.log(`License: ${manifest.license}`);
  console.log("");
  console.log("Used by:");
  console.log(`  ${pkg.name} ${pkg.version}${repo ? ` (${repo})` : ""}`);
  console.log("");
  if (files.length === 0) {
    // 本文の無い package を黙って通すと、notices から本文が抜けたことに誰も気付かない。
    // 許すのは Tauri プラグインの JS 側だけ: 同じリポジトリ・同じライセンスの Rust crate
    // (tauri-plugin-<name>) が Rust 節に本文付きで載るので、そちらを指す
    const plugin = pkg.name.match(/^@tauri-apps\/plugin-(.+)$/);
    const crate = plugin && `tauri-plugin-${plugin[1]}`;
    if (!crate || !crates.has(crate)) {
      throw new Error(`${pkg.name} ships no license file; add its license text by hand`);
    }
    console.log("The package does not ship its license text. It is the JavaScript side of the");
    console.log(`${crate} crate listed under Rust crates below, published from the same`);
    console.log("repository under the same license.");
    console.log("");
    continue;
  }
  for (const f of files) {
    if (files.length > 1) console.log(`--- ${f} ---`);
    console.log(fs.readFileSync(path.join(pkg.dir, f), "utf8").replace(/\s+$/, ""));
    console.log("");
  }
}
NODE

  cat <<'HEADER'
################################################################################
# Rust crates (compiled into the binary)
################################################################################

HEADER

  # --fail: ライセンスを特定できない crate があれば警告で省略せず失敗させる
  cargo about generate --manifest-path src-tauri/Cargo.toml --locked --fail src-tauri/about.hbs

  cat <<'HEADER'
################################################################################
# Native libraries (C and C++ sources shipped inside the crates above, linked statically)
################################################################################

HEADER

  METADATA_JSON="$METADATA_JSON" node - <<'NODE'
const fs = require("fs");
const path = require("path");

// crate, library, SPDX, files (crate ディレクトリからの相対パス。null は本文なしの注記)
const NATIVE = [
  ["openssl-src", "OpenSSL", "Apache-2.0", ["openssl/LICENSE.txt"]],
  ["libssh2-sys", "libssh2", "BSD-3-Clause", ["libssh2/COPYING"]],
  // macOS は OS の libz をリンクし、Windows ではこのソースから静的にビルドする
  ["libz-sys", "zlib", "Zlib", ["src/zlib/LICENSE"]],
  ["libsqlite3-sys", "SQLite", "blessing", null],
];

const metadata = JSON.parse(fs.readFileSync(process.env.METADATA_JSON, "utf8"));
for (const [crate, library, license, files] of NATIVE) {
  const found = metadata.packages.filter((p) => p.name === crate);
  if (found.length !== 1) {
    throw new Error(`${crate}: expected exactly one package in cargo metadata, found ${found.length}`);
  }
  const pkg = found[0];
  const dir = path.dirname(pkg.manifest_path);
  console.log("=".repeat(80));
  console.log(`License: ${license}`);
  console.log("");
  console.log("Used by:");
  console.log(`  ${library} (bundled by ${crate} ${pkg.version})`);
  console.log("");
  if (files === null) {
    console.log(
      "The SQLite source code is in the public domain (https://sqlite.org/copyright.html).",
    );
    console.log("");
    continue;
  }
  for (const f of files) {
    console.log(fs.readFileSync(path.join(dir, f), "utf8").replace(/\s+$/, ""));
    console.log("");
  }
}

// DuckDB (libduckdb-sys の bundled) は third_party/ に他のライブラリを同梱してまとめて
// 静的リンクする。crate の tarball にはそれらのライセンスファイルが入っていないので、
// tarball が同梱している DuckDB の version を読み、同じタグの DuckDB リポジトリから
// third_party/<dir>/ のライセンスファイルを取ってくる。
// 未知のディレクトリが増えたら止める: ライセンスを確かめずに載せると、GPL のような
// 配布条件の変わるものが紛れても気付けないため。確かめてからここに足す。
const DUCKDB_THIRD_PARTY = {
  brotli: "MIT",
  concurrentqueue: "BSD-2-Clause OR BSL-1.0",
  fast_float: "MIT",
  fastpforlib: "Apache-2.0",
  fmt: "MIT",
  fsst: "MIT",
  httplib: "MIT",
  hyperloglog: "MIT",
  jaro_winkler: "MIT",
  libpg_query: "BSD-3-Clause",
  lz4: "BSD-2-Clause",
  mbedtls: "Apache-2.0 OR GPL-2.0-or-later (used under Apache-2.0)",
  miniz: "MIT",
  parquet: "Apache-2.0",
  pcg: "MIT",
  pdqsort: "Zlib",
  re2: "BSD-3-Clause",
  ska_sort: "BSL-1.0",
  skiplist: "MIT",
  snappy: "BSD-3-Clause",
  tdigest: "Apache-2.0",
  thrift: "Apache-2.0",
  utf8proc: "MIT AND Unicode-DFS-2015",
  vergesort: "MIT",
  yyjson: "MIT",
  zstd: "BSD-3-Clause",
};

(async () => {
  const { execFileSync } = require("child_process");
  const [duckdbSys] = metadata.packages.filter((p) => p.name === "libduckdb-sys");
  if (!duckdbSys) throw new Error("libduckdb-sys is not in cargo metadata");
  const tarball = path.join(path.dirname(duckdbSys.manifest_path), "duckdb.tar.gz");
  const pragma = execFileSync(
    "tar",
    ["xzf", tarball, "-O", "duckdb/src/function/table/version/pragma_version.cpp"],
    { encoding: "utf8" },
  );
  const tag = pragma.match(/#define DUCKDB_VERSION "(v[0-9.]+)"/)?.[1];
  if (!tag) throw new Error("could not read DUCKDB_VERSION from the libduckdb-sys tarball");
  const dirs = [
    ...new Set(
      execFileSync("tar", ["tzf", tarball], { encoding: "utf8", maxBuffer: 64 << 20 })
        .split("\n")
        .map((line) => line.match(/^duckdb\/third_party\/([^/]+)\//)?.[1])
        .filter(Boolean),
    ),
  ].sort();
  const unknown = dirs.filter((d) => !(d in DUCKDB_THIRD_PARTY));
  if (unknown.length) {
    throw new Error(`DuckDB vendors libraries with unchecked licenses: ${unknown.join(", ")}`);
  }

  const tree = await fetch(`https://api.github.com/repos/duckdb/duckdb/git/trees/${tag}?recursive=1`);
  if (!tree.ok) throw new Error(`GitHub tree API for duckdb ${tag}: HTTP ${tree.status}`);
  const paths = (await tree.json()).tree.filter((e) => e.type === "blob").map((e) => e.path);
  for (const dir of dirs) {
    const files = paths
      .filter((p) => p.startsWith(`third_party/${dir}/`))
      .filter((p) => /^(LICEN[CS]E|COPYING|NOTICE)/i.test(path.basename(p)))
      .sort();
    if (files.length === 0) throw new Error(`no license file for duckdb third_party/${dir} at ${tag}`);
    console.log("=".repeat(80));
    console.log(`License: ${DUCKDB_THIRD_PARTY[dir]}`);
    console.log("");
    console.log("Used by:");
    console.log(`  ${dir} (bundled by libduckdb-sys ${duckdbSys.version})`);
    console.log("");
    for (const f of files) {
      const url = `https://raw.githubusercontent.com/duckdb/duckdb/${tag}/${f}`;
      const res = await fetch(url);
      if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
      if (files.length > 1) console.log(`--- ${f.slice(`third_party/${dir}/`.length)} ---`);
      console.log((await res.text()).replace(/\s+$/, ""));
      console.log("");
    }
  }
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
NODE
} > "$TMP"

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
