#!/usr/bin/env bash
# Write the licenses of the dependency libraries included in the distribution to THIRD-PARTY-NOTICES.txt.
# Called from `pnpm notices`. Re-run and commit it whenever dependencies are added or bumped
# (a test in lib.rs checks that the direct dependencies are listed in this file).
#
# There are 3 sections:
# - JavaScript: package.json dependencies, transitively (pnpm licenses list --prod).
#   In addition, packages that are in devDependencies but get bundled into the webview by the build
#   are listed in BUNDLED_DEV_PACKAGES (the svelte / SvelteKit runtime, svelte-sonner and its
#   dependencies, tailwindcss which ends up in the CSS, and bootstrap-icons which ships the font).
#   This list was determined by having `vite build` emit a sourcemap and counting the node_modules
#   packages that appear in its sources. If you add a devDependency that gets bundled, add it here too.
# - Rust: cargo-about (`cargo install cargo-about --locked --features cli`).
#   The config is src-tauri/about.toml and the format is src-tauri/about.hbs.
# - Native: libraries that crates ship C / C++ sources for and link statically (OpenSSL / libssh2 /
#   zlib / SQLite / what DuckDB bundles in third_party). The crate's own license appears in the Rust
#   section, but the license of the library it bundles is a separate one, so we read the text from the
#   crate's source (for DuckDB, the DuckDB repository at the tag of the same version; this needs a
#   network connection to GitHub) and include it.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD-PARTY-NOTICES.txt"

if ! cargo about --version >/dev/null 2>&1; then
  echo "Error: cargo-about is not installed. Run: cargo install cargo-about --locked --features cli" >&2
  exit 1
fi
if [ ! -d node_modules ]; then
  echo "Error: node_modules is missing. Run: pnpm install" >&2
  exit 1
fi

# Create it in the same directory. An mv from /tmp on a different filesystem becomes a copy, and
# if it stops midway a broken output is left behind
TMP=$(mktemp "${OUT}.XXXXXX")
PROD_JSON=$(mktemp "${OUT}.prod.XXXXXX")
ALL_JSON=$(mktemp "${OUT}.all.XXXXXX")
METADATA_JSON=$(mktemp "${OUT}.meta.XXXXXX")
trap 'rm -f "$TMP" "$PROD_JSON" "$ALL_JSON" "$METADATA_JSON"' EXIT

pnpm licenses list --prod --json > "$PROD_JSON"
pnpm licenses list --json > "$ALL_JSON"
cargo metadata --manifest-path src-tauri/Cargo.toml --locked --format-version 1 > "$METADATA_JSON"

{
  cat <<'HEADER'
THIRD-PARTY NOTICES

Queryfolio bundles the open source libraries listed below. Each entry gives the
license, the packages it applies to, and the license text as shipped by the
package. Generated by scripts/generate-third-party-notices.sh; do not edit by hand.

################################################################################
# JavaScript packages (bundled into the web view)
################################################################################

HEADER

  PROD_JSON="$PROD_JSON" ALL_JSON="$ALL_JSON" METADATA_JSON="$METADATA_JSON" node - <<'NODE'
const fs = require("fs");
const path = require("path");

const crates = new Set(
  JSON.parse(fs.readFileSync(process.env.METADATA_JSON, "utf8")).packages.map((p) => p.name),
);

const BUNDLED_DEV_PACKAGES = [
  "@sveltejs/kit",
  "bootstrap-icons",
  "clsx",
  "esm-env",
  "runed",
  "svelte",
  "svelte-sonner",
  "tailwindcss",
];

const flatten = (file) =>
  Object.values(JSON.parse(fs.readFileSync(file, "utf8"))).flat();

const packages = new Map();
const add = (entry) => {
  if (entry.versions.length !== 1) {
    // If multiple versions are present, we cannot decide here which one was bundled
    throw new Error(`${entry.name} has several versions: ${entry.versions.join(", ")}`);
  }
  packages.set(entry.name, { name: entry.name, version: entry.versions[0], dir: entry.paths[0] });
};
for (const entry of flatten(process.env.PROD_JSON)) add(entry);
const all = flatten(process.env.ALL_JSON);
for (const name of BUNDLED_DEV_PACKAGES) {
  const entry = all.find((e) => e.name === name);
  if (!entry) throw new Error(`${name} is not installed`);
  add(entry);
}

for (const pkg of [...packages.values()].sort((a, b) => a.name.localeCompare(b.name))) {
  const manifest = JSON.parse(fs.readFileSync(path.join(pkg.dir, "package.json"), "utf8"));
  const repo =
    typeof manifest.repository === "string" ? manifest.repository : manifest.repository?.url;
  // SPDX metadata such as LICENSE.spdx is not license text, so exclude it
  const files = fs
    .readdirSync(pkg.dir)
    .filter((f) => /^(LICEN[CS]E|COPYING|NOTICE)/i.test(f) && !/\.spdx$/i.test(f))
    .sort();
  console.log("=".repeat(80));
  console.log(`License: ${manifest.license}`);
  console.log("");
  console.log("Used by:");
  console.log(`  ${pkg.name} ${pkg.version}${repo ? ` (${repo})` : ""}`);
  console.log("");
  if (files.length === 0) {
    // Silently letting through a package with no license text would let the text vanish from the notices
    // unnoticed. Only the JS side of Tauri plugins is allowed: the Rust crate with the same repository and
    // same license (tauri-plugin-<name>) appears in the Rust section with its text, so point to that
    const plugin = pkg.name.match(/^@tauri-apps\/plugin-(.+)$/);
    const crate = plugin && `tauri-plugin-${plugin[1]}`;
    if (!crate || !crates.has(crate)) {
      throw new Error(`${pkg.name} ships no license file; add its license text by hand`);
    }
    console.log("The package does not ship its license text. It is the JavaScript side of the");
    console.log(`${crate} crate listed under Rust crates below, published from the same`);
    console.log("repository under the same license.");
    console.log("");
    continue;
  }
  for (const f of files) {
    if (files.length > 1) console.log(`--- ${f} ---`);
    console.log(fs.readFileSync(path.join(pkg.dir, f), "utf8").replace(/\s+$/, ""));
    console.log("");
  }
}
NODE

  cat <<'HEADER'
################################################################################
# Rust crates (compiled into the binary)
################################################################################

HEADER

  # --fail: if there is a crate whose license cannot be identified, fail instead of omitting it with a warning
  cargo about generate --manifest-path src-tauri/Cargo.toml --locked --fail src-tauri/about.hbs

  cat <<'HEADER'
################################################################################
# Native libraries (C and C++ sources shipped inside the crates above, linked statically)
################################################################################

HEADER

  METADATA_JSON="$METADATA_JSON" node - <<'NODE'
const fs = require("fs");
const path = require("path");

// crate, library, SPDX, files (paths relative to the crate directory; null is a note with no text)
const NATIVE = [
  ["openssl-src", "OpenSSL", "Apache-2.0", ["openssl/LICENSE.txt"]],
  ["libssh2-sys", "libssh2", "BSD-3-Clause", ["libssh2/COPYING"]],
  // macOS links the OS's libz; on Windows it is built statically from this source
  ["libz-sys", "zlib", "Zlib", ["src/zlib/LICENSE"]],
  ["libsqlite3-sys", "SQLite", "blessing", null],
];

const metadata = JSON.parse(fs.readFileSync(process.env.METADATA_JSON, "utf8"));
for (const [crate, library, license, files] of NATIVE) {
  const found = metadata.packages.filter((p) => p.name === crate);
  if (found.length !== 1) {
    throw new Error(`${crate}: expected exactly one package in cargo metadata, found ${found.length}`);
  }
  const pkg = found[0];
  const dir = path.dirname(pkg.manifest_path);
  console.log("=".repeat(80));
  console.log(`License: ${license}`);
  console.log("");
  console.log("Used by:");
  console.log(`  ${library} (bundled by ${crate} ${pkg.version})`);
  console.log("");
  if (files === null) {
    console.log(
      "The SQLite source code is in the public domain (https://sqlite.org/copyright.html).",
    );
    console.log("");
    continue;
  }
  for (const f of files) {
    console.log(fs.readFileSync(path.join(dir, f), "utf8").replace(/\s+$/, ""));
    console.log("");
  }
}

// DuckDB (libduckdb-sys's bundled) ships other libraries in third_party/ and links them all statically.
// The crate tarball does not include their license files, so we read the DuckDB version the tarball
// bundles and fetch the license files under third_party/<dir>/ from the DuckDB repository at the same tag.
// Stop when an unknown directory appears: if we included it without checking the license, something
// like a GPL component with different distribution terms could slip in unnoticed. Check it, then add it here.
const DUCKDB_THIRD_PARTY = {
  brotli: "MIT",
  concurrentqueue: "BSD-2-Clause OR BSL-1.0",
  fast_float: "MIT",
  fastpforlib: "Apache-2.0",
  fmt: "MIT",
  fsst: "MIT",
  httplib: "MIT",
  hyperloglog: "MIT",
  jaro_winkler: "MIT",
  libpg_query: "BSD-3-Clause",
  lz4: "BSD-2-Clause",
  mbedtls: "Apache-2.0 OR GPL-2.0-or-later (used under Apache-2.0)",
  miniz: "MIT",
  parquet: "Apache-2.0",
  pcg: "MIT",
  pdqsort: "Zlib",
  re2: "BSD-3-Clause",
  ska_sort: "BSL-1.0",
  skiplist: "MIT",
  snappy: "BSD-3-Clause",
  tdigest: "Apache-2.0",
  thrift: "Apache-2.0",
  utf8proc: "MIT AND Unicode-DFS-2015",
  vergesort: "MIT",
  yyjson: "MIT",
  zstd: "BSD-3-Clause",
};

(async () => {
  const { execFileSync } = require("child_process");
  const [duckdbSys] = metadata.packages.filter((p) => p.name === "libduckdb-sys");
  if (!duckdbSys) throw new Error("libduckdb-sys is not in cargo metadata");
  const tarball = path.join(path.dirname(duckdbSys.manifest_path), "duckdb.tar.gz");
  const pragma = execFileSync(
    "tar",
    ["xzf", tarball, "-O", "duckdb/src/function/table/version/pragma_version.cpp"],
    { encoding: "utf8" },
  );
  const tag = pragma.match(/#define DUCKDB_VERSION "(v[0-9.]+)"/)?.[1];
  if (!tag) throw new Error("could not read DUCKDB_VERSION from the libduckdb-sys tarball");
  const dirs = [
    ...new Set(
      execFileSync("tar", ["tzf", tarball], { encoding: "utf8", maxBuffer: 64 << 20 })
        .split("\n")
        .map((line) => line.match(/^duckdb\/third_party\/([^/]+)\//)?.[1])
        .filter(Boolean),
    ),
  ].sort();
  const unknown = dirs.filter((d) => !(d in DUCKDB_THIRD_PARTY));
  if (unknown.length) {
    throw new Error(`DuckDB vendors libraries with unchecked licenses: ${unknown.join(", ")}`);
  }

  const tree = await fetch(`https://api.github.com/repos/duckdb/duckdb/git/trees/${tag}?recursive=1`);
  if (!tree.ok) throw new Error(`GitHub tree API for duckdb ${tag}: HTTP ${tree.status}`);
  const paths = (await tree.json()).tree.filter((e) => e.type === "blob").map((e) => e.path);
  for (const dir of dirs) {
    const files = paths
      .filter((p) => p.startsWith(`third_party/${dir}/`))
      .filter((p) => /^(LICEN[CS]E|COPYING|NOTICE)/i.test(path.basename(p)))
      .sort();
    if (files.length === 0) throw new Error(`no license file for duckdb third_party/${dir} at ${tag}`);
    console.log("=".repeat(80));
    console.log(`License: ${DUCKDB_THIRD_PARTY[dir]}`);
    console.log("");
    console.log("Used by:");
    console.log(`  ${dir} (bundled by libduckdb-sys ${duckdbSys.version})`);
    console.log("");
    for (const f of files) {
      const url = `https://raw.githubusercontent.com/duckdb/duckdb/${tag}/${f}`;
      const res = await fetch(url);
      if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
      if (files.length > 1) console.log(`--- ${f.slice(`third_party/${dir}/`.length)} ---`);
      console.log((await res.text()).replace(/\s+$/, ""));
      console.log("");
    }
  }
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
NODE
} > "$TMP"

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
