//! Generates the metadata file that describes the connection, placed in the query-file folder.
//!
//! Each connection's query files are stored in `<sqlfiles_dir>/<folder>/*.sql`.
//! So that AI agents (sql-agent family or coding agents) and humans opening that folder can
//! tell which DB and what purpose the queries are for, the connection's non-secret metadata
//! is written out as Markdown.
//!
//! Secrets (passwords, SSH keys, passphrases) must never be included. Only information that
//! ConnectionInfo already hands to the frontend is included (name / description /
//! engine / host / port / schema / user / readonly / group / whether an SSH tunnel is
//! used).

use std::fs;
use std::path::Path;

use crate::config::ServerConfig;
use crate::error::AppError;

/// Metadata file name. It is not `.sql`, so it does not appear in the query-file list or search
/// (which only cover .sql). It does not start with a dot, so it is visible to agents / Finder.
pub const META_FILE_NAME: &str = "_queryfolio.md";

/// Formats an Option<String> for display (None / whitespace-only becomes "-").
fn field(value: Option<&str>) -> String {
    match value.map(str::trim) {
        Some(v) if !v.is_empty() => v.to_string(),
        _ => "-".to_string(),
    }
}

/// Generates Markdown from the connection's non-secret metadata.
pub fn render_meta(server: &ServerConfig) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Queryfolio — {}\n\n", server.name));

    if let Some(desc) = server.description.as_deref() {
        let desc = desc.trim();
        if !desc.is_empty() {
            out.push_str(desc);
            out.push_str("\n\n");
        }
    }

    out.push_str(
        "This file is auto-generated by Queryfolio and describes the database \
connection whose SQL query files are stored in this folder. It exists so that \
AI agents and humans can understand what these queries target. Manual edits are \
overwritten. No secrets (passwords, SSH keys) are included.\n\n",
    );

    out.push_str(&format!("- **Connection:** {}\n", server.name));
    out.push_str(&format!("- **Engine:** {}\n", server.engine));
    out.push_str(&format!("- **Host:** {}\n", field(server.host.as_deref())));
    out.push_str(&format!(
        "- **Port:** {}\n",
        server.port.map(|p| p.to_string()).unwrap_or_else(|| "-".into())
    ));
    out.push_str(&format!(
        "- **Database (schema):** {}\n",
        field(server.schema.as_deref())
    ));
    // For dynamodb the user is an AWS access key ID (a credential identifier), so
    // it is not written to the metadata file
    let user_display = if server.engine.eq_ignore_ascii_case("dynamodb") {
        server.user.as_ref().map(|_| "(aws access key, hidden)")
    } else {
        server.user.as_deref()
    };
    out.push_str(&format!("- **User:** {}\n", field(user_display)));
    out.push_str(&format!(
        "- **Read-only:** {}\n",
        if server.readonly { "yes" } else { "no" }
    ));
    out.push_str(&format!(
        "- **Group:** {}\n",
        field(server.group_name.as_deref())
    ));

    let ssh = match server.ssh_tunnel.as_ref() {
        Some(t) => match t.ssh_config.as_deref() {
            Some(alias) if !alias.trim().is_empty() => {
                format!("via ssh_config host '{}'", alias.trim())
            }
            _ => format!("via {}@{}:{}", t.user, t.host, t.port),
        },
        None => "no".to_string(),
    };
    out.push_str(&format!("- **SSH tunnel:** {ssh}\n"));

    out
}

/// Writes the metadata file into the folder.
///
/// - Does nothing if the folder does not exist (no empty folder is created just for metadata).
/// - Does not write if the content is identical to the existing one (avoids mtime churn).
pub fn write_folder_meta(dir: &Path, server: &ServerConfig) -> Result<(), AppError> {
    if !dir.is_dir() {
        return Ok(());
    }
    let content = render_meta(server);
    let path = dir.join(META_FILE_NAME);
    if let Ok(existing) = fs::read_to_string(&path) {
        if existing == content {
            return Ok(());
        }
    }
    fs::write(&path, content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base_server() -> ServerConfig {
        ServerConfig {
            name: "prod-db".to_string(),
            description: Some("Production orders database".to_string()),
            folder_name: None,
            engine: "postgres".to_string(),
            host: Some("db.example.com".to_string()),
            port: Some(5432),
            schema: Some("orders".to_string()),
            user: Some("app".to_string()),
            password: Some("s3cret".to_string()),
            ssh_tunnel: None,
            tls: false,
            ssl_mode: None,
            ssl_root_cert: None,
            aws_profile: None,
            readonly: true,
            allow_dangerous_statements: false,
            group_name: Some("Production".to_string()),
        }
    }

    #[test]
    fn test_render_meta_contains_fields_and_no_secret() {
        let meta = render_meta(&base_server());
        assert!(meta.contains("# Queryfolio — prod-db"));
        assert!(meta.contains("Production orders database"));
        assert!(meta.contains("- **Engine:** postgres"));
        assert!(meta.contains("- **Host:** db.example.com"));
        assert!(meta.contains("- **Port:** 5432"));
        assert!(meta.contains("- **Database (schema):** orders"));
        assert!(meta.contains("- **User:** app"));
        assert!(meta.contains("- **Read-only:** yes"));
        assert!(meta.contains("- **Group:** Production"));
        assert!(meta.contains("- **SSH tunnel:** no"));
        // Never include the password
        assert!(!meta.contains("s3cret"));
    }

    #[test]
    fn test_render_meta_optional_fields_dash() {
        let mut s = base_server();
        s.description = None;
        s.host = None;
        s.port = None;
        s.schema = Some("   ".to_string());
        s.user = None;
        s.readonly = false;
        s.group_name = None;
        let meta = render_meta(&s);
        assert!(meta.contains("- **Host:** -"));
        assert!(meta.contains("- **Port:** -"));
        assert!(meta.contains("- **Database (schema):** -"));
        assert!(meta.contains("- **User:** -"));
        assert!(meta.contains("- **Read-only:** no"));
        assert!(meta.contains("- **Group:** -"));
    }

    #[test]
    fn test_render_meta_ssh_tunnel_without_credentials() {
        let mut s = base_server();
        s.ssh_tunnel = Some(crate::config::SshTunnelConfig {
            host: "bastion.example.com".to_string(),
            port: 22,
            user: "tunnel".to_string(),
            ssh_config: None,
            password: Some("tunnelpass".to_string()),
            private_key_path: Some("/home/me/.ssh/id_ed25519".to_string()),
            private_key_passphrase: Some("keypass".to_string()),
            identity_agent: None,
        });
        let meta = render_meta(&s);
        assert!(meta.contains("- **SSH tunnel:** via tunnel@bastion.example.com:22"));
        // Do not include tunnel secrets either
        assert!(!meta.contains("tunnelpass"));
        assert!(!meta.contains("keypass"));
        assert!(!meta.contains("id_ed25519"));
    }

    #[test]
    fn test_write_folder_meta_skips_missing_dir() {
        let dir = std::env::temp_dir().join(format!(
            "queryfolio-meta-missing-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = fs::remove_dir_all(&dir);
        // Do not write if the folder does not exist (no empty folder is created either)
        write_folder_meta(&dir, &base_server()).unwrap();
        assert!(!dir.exists());
    }

    #[test]
    fn test_meta_file_does_not_appear_in_query_file_listing() {
        // Reproduce the lib.rs flow (create query file -> write metadata file) and
        // verify the metadata file does not appear in the query-file list / search (.sql only).
        use crate::query_files;

        let sqlfiles_dir = std::env::temp_dir().join(format!(
            "queryfolio-meta-listing-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = fs::remove_dir_all(&sqlfiles_dir);
        let folder = "db.example.com_postgres_orders_app";

        // Create one query file (this creates the folder)
        query_files::create_query_file(&sqlfiles_dir, folder, "report", "sql").unwrap();
        // Write the metadata file (equivalent to refresh_folder_meta in lib.rs)
        let dir = query_files::connection_dir(&sqlfiles_dir, folder).unwrap();
        write_folder_meta(&dir, &base_server()).unwrap();

        // The metadata file exists
        assert!(dir.join(META_FILE_NAME).exists());
        // but does not appear in the query-file list (.sql only)
        let files = query_files::list_query_files(&sqlfiles_dir, folder, "sql").unwrap();
        assert_eq!(files, vec!["report.sql"]);
        // Nor in search ("Production" in the content is the base_server group name, but
        // the metadata file is not .sql, so it is excluded from search)
        let hits =
            query_files::search_query_files(&sqlfiles_dir, folder, "Production", "sql").unwrap();
        assert!(hits.is_empty());

        let _ = fs::remove_dir_all(&sqlfiles_dir);
    }

    #[test]
    fn test_write_folder_meta_writes_and_is_idempotent() {
        let dir = std::env::temp_dir().join(format!(
            "queryfolio-meta-write-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let server = base_server();
        write_folder_meta(&dir, &server).unwrap();
        let path = dir.join(META_FILE_NAME);
        assert!(path.exists());
        let written = fs::read_to_string(&path).unwrap();
        assert_eq!(written, render_meta(&server));

        // If the content is identical, do not change mtime (skip the write)
        let mtime1 = fs::metadata(&path).unwrap().modified().unwrap();
        write_folder_meta(&dir, &server).unwrap();
        let mtime2 = fs::metadata(&path).unwrap().modified().unwrap();
        assert_eq!(mtime1, mtime2);

        let _ = fs::remove_dir_all(&dir);
    }
}
