//! List of licenses of the dependency libraries bundled with the distributed artifact.
//!
//! Embeds, at build time, THIRD-PARTY-NOTICES.txt at the repository root (generated by
//! `scripts/generate-third-party-notices.sh` = `pnpm notices`). `--license` and the menu item
//! Third-Party Licenses display it.
//!
//! The tests detect "dependencies were changed but `pnpm notices` was not re-run".

pub const NOTICES: &str = include_str!("../../THIRD-PARTY-NOTICES.txt");

#[cfg(test)]
mod tests {
    use super::NOTICES;

    const RUST_HEADING: &str = "# Rust crates";
    const NATIVE_HEADING: &str = "# Native libraries";

    /// On Windows, checkouts get CRLF via autocrlf, so normalize line endings before reading
    /// (otherwise searches that include newlines, such as `"\nimporters:\n"`, miss).
    fn lf(text: &str) -> String {
        text.replace("\r\n", "\n")
    }

    /// Pick up the names of direct-dependency crates that ship in the distributed artifact from
    /// Cargo.toml. Only lines starting with `name = ...` under `[dependencies]` and
    /// `[target.'cfg(..)'.dependencies]` are examined (the `[dependencies.foo]` form is not picked
    /// up). Continuation lines of multi-line values do not have the `name =` shape, so they are not
    /// picked up. Build / dev dependencies do not ship, so they are excluded. If a target
    /// dependency specific to a target that is not distributed (Linux) is added, it is outside the
    /// targets in about.toml and absent from the notices, so this test fails; exclude it here then.
    fn direct_rust_dependencies(manifest: &str) -> Vec<String> {
        let mut section = String::new();
        let mut names = Vec::new();
        for line in manifest.lines() {
            if line.starts_with('[') {
                section = line.trim().to_string();
                continue;
            }
            let shipped = section == "[dependencies]"
                || (section.starts_with("[target.") && section.ends_with(".dependencies]"));
            // Continuation lines of a value (feature lists, etc.) are indented
            if !shipped || line.starts_with(|c: char| c.is_whitespace() || c == '#') {
                continue;
            }
            if let Some((name, _)) = line.split_once('=') {
                let name = name.trim();
                if !name.is_empty() && !name.contains(|c: char| c == '"' || c == ']') {
                    names.push(name.to_string());
                }
            }
        }
        names
    }

    /// Names of the package.json dependencies (runtime dependencies bundled into the webview).
    fn direct_npm_dependencies() -> Vec<String> {
        let package: serde_json::Value =
            serde_json::from_str(include_str!("../../package.json")).expect("package.json parses");
        package["dependencies"]
            .as_object()
            .expect("package.json has dependencies")
            .keys()
            .cloned()
            .collect()
    }

    /// Body of a notices section (npm / rust / native). Split by the heading lines.
    fn section<'a>(notices: &'a str, name: &str) -> &'a str {
        let (npm, rest) = notices
            .split_once(RUST_HEADING)
            .expect("the notices file has a Rust crates heading");
        let (rust, native) = rest
            .split_once(NATIVE_HEADING)
            .expect("the notices file has a Native libraries heading");
        match name {
            "npm" => npm,
            "rust" => rust,
            "native" => native,
            _ => panic!("unknown section {name}"),
        }
    }

    /// Lines listed in the "Used by:" block of THIRD-PARTY-NOTICES.txt (with the leading 2 spaces
    /// removed). Entries in the generated file are ordered as separator line -> `License: ...` ->
    /// blank line -> "Used by:", and only that sequence is read as a block (the same text inside a
    /// license body is not counted).
    fn used_by_lines(text: &str) -> Vec<String> {
        let separator = "=".repeat(80);
        let mut lines = Vec::new();
        let mut in_block = false;
        let mut after_separator = false;
        let mut after_license = false;
        for line in text.lines() {
            if in_block {
                match line.strip_prefix("  ") {
                    Some(rest) if !rest.is_empty() => lines.push(rest.to_string()),
                    _ => in_block = false,
                }
                continue;
            }
            in_block = after_license && line == "Used by:";
            after_license = (after_separator && line.starts_with("License: "))
                || (after_license && line.is_empty());
            after_separator = line == separator;
        }
        lines
    }

    /// (package name, version) of the npm / rust sections. Lines look like `name version (repository)`.
    fn packages_in_notices(notices: &str, name: &str) -> Vec<(String, String)> {
        used_by_lines(section(notices, name))
            .iter()
            .map(|line| {
                let mut words = line.split(' ');
                let package = words.next().unwrap_or_default().to_string();
                let version = words.next().unwrap_or_default().to_string();
                (package, version)
            })
            .collect()
    }

    /// (crate name, version) of the native section. Lines look like `<library> (bundled by <crate> <version>)`.
    fn native_crates_in_notices(notices: &str) -> Vec<(String, String)> {
        used_by_lines(section(notices, "native"))
            .iter()
            .map(|line| {
                let inner = line
                    .split_once("(bundled by ")
                    .and_then(|(_, rest)| rest.strip_suffix(')'))
                    .unwrap_or_else(|| panic!("unexpected native entry: {line}"));
                let (name, version) = inner.split_once(' ').expect("crate and version");
                (name.to_string(), version.to_string())
            })
            .collect()
    }

    /// A [[package]] block of Cargo.lock: (name, version, dependencies lines).
    fn locked_rust_packages(lock: &str) -> Vec<(String, String, Vec<String>)> {
        lock.split("[[package]]")
            .skip(1)
            .map(|block| {
                let field = |key: &str| {
                    block
                        .lines()
                        .find_map(|line| line.strip_prefix(key))
                        .map(|rest| rest.trim().trim_matches('"').to_string())
                        .unwrap_or_default()
                };
                let deps = block
                    .lines()
                    .filter_map(|line| line.strip_prefix(" \""))
                    .map(|line| line.trim_end_matches("\",").to_string())
                    .collect();
                (field("name = "), field("version = "), deps)
            })
            .collect()
    }

    /// The version Cargo.lock chose for queryfolio's direct dependency `name`. When the same crate
    /// is present in two or more versions, it is written in the root dependencies as `name version`.
    fn resolved_rust_version(lock: &[(String, String, Vec<String>)], name: &str) -> String {
        let root = lock
            .iter()
            .find(|(crate_name, _, _)| crate_name == "queryfolio")
            .expect("Cargo.lock has the queryfolio package");
        let entry = root
            .2
            .iter()
            .find(|dep| *dep == name || dep.starts_with(&format!("{name} ")))
            .unwrap_or_else(|| panic!("{name} is not a dependency of queryfolio in Cargo.lock"));
        // When the name and version are the same but the source differs it becomes `name version (source)`, so only the second word is taken
        match entry.split(' ').nth(1) {
            Some(version) => version.to_string(),
            None => {
                let mut versions = lock
                    .iter()
                    .filter(|(crate_name, _, _)| crate_name == name)
                    .map(|(_, version, _)| version.clone());
                let version = versions.next().expect("the crate is in Cargo.lock");
                assert!(
                    versions.next().is_none(),
                    "{name} has several versions in Cargo.lock"
                );
                version
            }
        }
    }

    /// The (name, version) that the importers `.` entry (this project) of pnpm-lock.yaml chose for
    /// `group` (`dependencies` / `devDependencies`).
    /// Laid out as 3 lines: `name:` -> `specifier:` -> `version:`.
    fn resolved_npm_versions(lock: &str, group: &str) -> Vec<(String, String)> {
        let header = format!("    {group}:");
        let importer = lock
            .split("\nimporters:\n")
            .nth(1)
            .expect("pnpm-lock.yaml has an importers section")
            .split("\npackages:\n")
            .next()
            .expect("importers come before packages");
        let mut resolved = Vec::new();
        let mut name = String::new();
        let mut in_dependencies = false;
        for line in importer.lines() {
            if line.starts_with("    ") && !line.starts_with("     ") {
                in_dependencies = line == header;
                continue;
            }
            if !in_dependencies {
                continue;
            }
            if let Some(key) = line
                .strip_prefix("      ")
                .filter(|rest| !rest.starts_with(' '))
            {
                name = key.trim_end_matches(':').trim_matches('\'').to_string();
            } else if let Some(version) = line.strip_prefix("        version: ") {
                // The parentheses of peer dependencies are absent from the notices version
                let version = version.split('(').next().unwrap_or(version).trim();
                resolved.push((name.clone(), version.to_string()));
            }
        }
        resolved
    }

    /// All (name, version) pairs listed in the packages section of pnpm-lock.yaml. Keys look like
    /// `name@version:` (scoped ones are quoted). Used to match transitive dependencies and bundled devDependencies.
    fn locked_npm_packages(lock: &str) -> Vec<(String, String)> {
        let packages = lock
            .split("\npackages:\n")
            .nth(1)
            .expect("pnpm-lock.yaml has a packages section")
            .split("\nsnapshots:\n")
            .next()
            .expect("packages come before snapshots");
        packages
            .lines()
            .filter_map(|line| line.strip_prefix("  "))
            .filter(|rest| !rest.starts_with(' ') && rest.ends_with(':'))
            .filter_map(|key| {
                let key = key.trim_end_matches(':').trim_matches('\'');
                // For scoped `@scope/name@1.0.0`, skip the leading @ when splitting
                let at = key[1..].find('@')? + 1;
                Some((key[..at].to_string(), key[at + 1..].to_string()))
            })
            .collect()
    }

    /// `--license` and the menu print this string as is, so it must have the heading and the 3 sections.
    #[test]
    fn notices_have_the_heading_and_every_section() {
        let notices = lf(NOTICES);
        assert!(notices.starts_with("THIRD-PARTY NOTICES\n"));
        for heading in ["# JavaScript packages", RUST_HEADING, NATIVE_HEADING] {
            assert!(notices.contains(heading), "missing {heading}");
        }
    }

    /// Whether each direct dependency is listed with the version Cargo.lock chose. With names alone,
    /// it would pass when an old version of an upgraded dependency remains as a transitive dependency.
    #[test]
    fn third_party_notices_list_every_direct_rust_dependency() {
        // Arrange
        let deps = direct_rust_dependencies(&lf(include_str!("../Cargo.toml")));
        assert!(deps.contains(&"tauri".to_string()), "parsed deps: {deps:?}");
        assert!(deps.contains(&"sqlx".to_string()), "parsed deps: {deps:?}");
        assert!(
            !deps.contains(&"tempfile".to_string()),
            "parsed deps: {deps:?}"
        );
        let lock = locked_rust_packages(&lf(include_str!("../Cargo.lock")));
        let listed = packages_in_notices(&lf(NOTICES), "rust");
        assert!(listed.len() > 100, "parsed notices: {listed:?}");

        // Act
        let missing: Vec<(String, String)> = deps
            .iter()
            .map(|name| (name.clone(), resolved_rust_version(&lock, name)))
            .filter(|entry| !listed.contains(entry))
            .collect();

        // Assert
        assert!(
            missing.is_empty(),
            "not in THIRD-PARTY-NOTICES.txt (run `pnpm notices`): {missing:?}"
        );
    }

    /// If the version of a listed crate disagrees with Cargo.lock, a dependency was upgraded but
    /// `pnpm notices` was not re-run. The same applies to crates in the native section.
    #[test]
    fn third_party_notices_match_cargo_lock_versions() {
        // Arrange
        let lock = locked_rust_packages(&lf(include_str!("../Cargo.lock")));
        let notices = lf(NOTICES);
        let mut listed = packages_in_notices(&notices, "rust");
        assert!(listed.len() > 100, "parsed notices: {listed:?}");
        let native = native_crates_in_notices(&notices);
        assert!(native.len() >= 3, "parsed native entries: {native:?}");
        listed.extend(native);

        // Act
        let stale: Vec<&(String, String)> = listed
            .iter()
            .filter(|(name, version)| !lock.iter().any(|(n, v, _)| n == name && v == version))
            .collect();

        // Assert
        assert!(
            stale.is_empty(),
            "not in Cargo.lock (run `pnpm notices`): {stale:?}"
        );
    }

    /// Whether direct dependencies are listed with the version chosen by pnpm-lock.yaml, and every
    /// listed package exists in the lock. The npm side of the notices is written from node_modules'
    /// package.json, so updating the lock but forgetting to install and regenerate leaves old versions.
    #[test]
    fn third_party_notices_match_pnpm_lock() {
        // Arrange
        let deps = direct_npm_dependencies();
        assert!(
            deps.contains(&"@codemirror/view".to_string()),
            "parsed deps: {deps:?}"
        );
        let lock = lf(include_str!("../../pnpm-lock.yaml"));
        let resolved = resolved_npm_versions(&lock, "dependencies");
        assert_eq!(
            resolved.len(),
            deps.len(),
            "parsed lock importer: {resolved:?}"
        );
        let locked = locked_npm_packages(&lock);
        assert!(locked.len() > 100, "parsed lock packages: {locked:?}");
        let dev = resolved_npm_versions(&lock, "devDependencies");
        assert!(
            dev.iter().any(|(name, _)| name == "svelte"),
            "parsed lock importer: {dev:?}"
        );
        let listed = packages_in_notices(&lf(NOTICES), "npm");

        // Act
        let missing: Vec<&(String, String)> = resolved
            .iter()
            .filter(|entry| !listed.contains(entry))
            .collect();
        // Bundled devDependencies (svelte, etc.) would pass even if an old version remains in the lock
        // via another dependency path, so match against the version resolved as a direct dependency
        let stale_dev: Vec<&(String, String)> = listed
            .iter()
            .filter(|(name, version)| dev.iter().any(|(n, v)| n == name && v != version))
            .collect();
        let unknown: Vec<&(String, String)> = listed
            .iter()
            .filter(|entry| !locked.contains(entry))
            .collect();

        // Assert
        assert!(
            missing.is_empty(),
            "not in THIRD-PARTY-NOTICES.txt (run `pnpm notices`): {missing:?}"
        );
        assert!(
            unknown.is_empty(),
            "not in pnpm-lock.yaml (run `pnpm notices`): {unknown:?}"
        );
        assert!(
            stale_dev.is_empty(),
            "older than the devDependencies in pnpm-lock.yaml (run `pnpm notices`): {stale_dev:?}"
        );
    }

    /// The result must be the same on a Windows checkout (CRLF) too.
    #[test]
    fn notices_parsers_accept_crlf() {
        // Arrange
        let entry = |used_by: &str| {
            "=".repeat(80) + "\r\nLicense: MIT\r\n\r\nUsed by:\r\n  " + used_by + "\r\n\r\ntext\r\n"
        };
        let notices = "x\r\n".to_string()
            + &entry("yaml 2.9.0 (u)")
            + "# Rust crates\r\n\r\n"
            + &entry("serde 1.0.0 (u)")
            + "# Native libraries\r\n\r\n"
            + &entry("zlib (bundled by libz-sys 1.1.29)");
        let lock = "lockfileVersion: '9.0'\r\nimporters:\r\n  .:\r\n    dependencies:\r\n      yaml:\r\n        specifier: ^2\r\n        version: 2.9.0\r\npackages:\r\n  yaml@2.9.0:\r\n    x: y\r\n  '@a/b@1.0.0':\r\n    x: y\r\nsnapshots:\r\n";

        // Act
        let notices = lf(&notices);
        let lock = lf(lock);

        // Assert
        let pair = |a: &str, b: &str| (a.to_string(), b.to_string());
        assert_eq!(
            packages_in_notices(&notices, "npm"),
            vec![pair("yaml", "2.9.0")]
        );
        assert_eq!(
            packages_in_notices(&notices, "rust"),
            vec![pair("serde", "1.0.0")]
        );
        assert_eq!(
            native_crates_in_notices(&notices),
            vec![pair("libz-sys", "1.1.29")]
        );
        assert_eq!(
            resolved_npm_versions(&lock, "dependencies"),
            vec![pair("yaml", "2.9.0")]
        );
        assert_eq!(
            locked_npm_packages(&lock),
            vec![pair("yaml", "2.9.0"), pair("@a/b", "1.0.0")]
        );
    }

    /// Values spanning multiple lines in Cargo.toml (sqlx features, etc.) must not be mistaken for dependencies.
    #[test]
    fn direct_rust_dependencies_skip_continuation_lines() {
        // Arrange
        let manifest = "[package]\nname = \"x\"\n\n[dependencies]\nsqlx = { version = \"0.8\", features = [\n  \"mysql\",\n] }\n# comment = 1\nserde = \"1\"\n\n[dev-dependencies]\ntempfile = \"3\"\n\n[target.'cfg(windows)'.dependencies]\nwindows = \"0.1\"\n";

        // Act
        let deps = direct_rust_dependencies(manifest);

        // Assert
        assert_eq!(deps, vec!["sqlx", "serde", "windows"]);
    }
}
